### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by MarkJEverest** [VSoftTechnologies/FinalBuilder-VSO#1]
Hi,

I have followed your installation instructions, but when running:

> tfx build tasks upload ./FinalBuilder --overwrite

from the FinalBuilder-VSO folder created, I get the following error:

> Command './FinalBuilder' not found. For help, type tfx build tasks upload --help

**Comment by vincentparrett** [comment]
try without the --overwrite option for the first time. Also, it looks like they have added a new option since we released our task so this might work (will get someone to test it tomorrow, I don't have access right now)

tfx build tasks upload --task-path ./FinalBuilder

or

tfx build tasks upload --task-path ./FinalBuilder --overwrite

Also, make sure you run it from the root folder of the repository.

**Comment by MarkJEverest** [comment]
Hi Vincent,
Adding the "--task-path" option has worked thanks!
Mark

**Comment by vincentparrett** [comment]
Ok thanks for confirming, I have updated the doco with the option.
